/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TireProduct, TireType, FAQItem } from './types';

// 模拟的高端、中端轮胎产品数据库
export const TIRE_PRODUCTS: TireProduct[] = [
  {
    id: 'komatsu-sport-s1',
    brand: 'KOMATSU',
    name: 'EURO SPORT S1',
    type: TireType.SPORT,
    width: 225,
    aspectRatio: 40,
    diameter: 18,
    loadIndex: 92,
    speedRating: 'Y',
    priceYen: 18500,
    features: ['高极限抓地力', '湿地防滑配方', '超低滚动阻力'],
    description: '专为豪华轿车与运动轿车设计。不对称花纹设计在高速过弯时提供极致的侧向刚性，高硅湿地抓地力配方极大地缩短了湿雨天制动距离。',
    image: 'sport',
    popularity: 4.9,
  },
  {
    id: 'komatsu-comfort-silent',
    brand: 'KOMATSU',
    name: 'SILENT CRUISE C2',
    type: TireType.COMFORT,
    width: 215,
    aspectRatio: 60,
    diameter: 16,
    loadIndex: 95,
    speedRating: 'V',
    priceYen: 12800,
    features: ['多段变频消音', '双层高刚性胎侧', '舒缓路噪减震'],
    description: '通过独特的3D变频消音块设计，相比传统轮胎能降低多达25%的滚动噪音，提供极为宁静舒适的驾乘空间，适合高端家用及商务轿车。',
    image: 'comfort',
    popularity: 4.8,
  },
  {
    id: 'komatsu-eco-green',
    brand: 'KOMATSU',
    name: 'ECO-SAVER GREEN',
    type: TireType.ECO,
    width: 195,
    aspectRatio: 65,
    diameter: 15,
    loadIndex: 91,
    speedRating: 'H',
    priceYen: 8900,
    features: ['极低油耗结构', '耐磨纳米级配方', '长寿命高性价比'],
    description: '环保绿色出行首选。采用高分散型纳米白炭黑配方，降低热量产生与滚动阻力。超深耐磨花纹，让出行里程更长、更省油。',
    image: 'eco',
    popularity: 4.7,
  },
  {
    id: 'komatsu-suv-cross',
    brand: 'KOMATSU',
    name: 'TRAIL ADVENTURER MAX',
    type: TireType.SUV,
    width: 265,
    aspectRatio: 65,
    diameter: 17,
    loadIndex: 112,
    speedRating: 'H',
    priceYen: 21000,
    features: ['防刺骨胎面', '强劲全地形牵引', '防侧削越野胎侧'],
    description: 'SUV和轻卡全地形（A/T）轮胎。粗犷开放的花纹块能在泥地、沙石地段提供强大的越野牵引力，加厚加宽胎肩有效抵御尖锐石块划伤。',
    image: 'suv',
    popularity: 4.9,
  },
  {
    id: 'komatsu-winter-ice',
    brand: 'KOMATSU',
    name: 'BLIZZAK GUARD W3',
    type: TireType.WINTER,
    width: 205,
    aspectRatio: 55,
    diameter: 16,
    loadIndex: 94,
    speedRating: 'Q',
    priceYen: 14500,
    features: ['发泡吸水微孔橡胶', '密集锯齿状钢片', '极寒不硬化材质'],
    description: '顶级雪地轮胎。使用专研低阻发泡孔橡胶，迅速吸除冰面水膜，高密蜂窝型钢片设计能像利爪一般切入松软的积雪与湿滑的冰面。',
    image: 'winter',
    popularity: 4.8,
  }
];

// 常见问题解答 FAQ
export const FAQS: FAQItem[] = [
  {
    id: 'f1',
    category: 'selection',
    question: '我应该如何确认车的轮胎规格？',
    answer: '通常有三种方式：1. 观察现有轮胎的胎侧（例如 205/55 R16）；2. 查阅主驾驶位B柱贴纸上的标准胎压标识；3. 翻阅车主的车辆报废证（車検証）或用户使用手册。',
    questionJa: 'タイヤサイズの確認方法は？',
    answerJa: '主に3つの方法があります：1. 現在装着されているタイヤの側面を確認（例：205/55 R16）、2. 運転席ドアのBピラー（柱部分）に貼ってある規格・空気圧シールを確認、3. 車検証（自動車検査証）やオーナーズマニュアルで推奨サイズを確認できます。',
  },
  {
    id: 'f2',
    category: 'maintenance',
    question: '大约多长时间需要更换新轮胎？',
    answer: '主要根据两个指标：1. 磨损深度：轮胎花纹沟槽中设有1.6mm磨损标记，当磨损至此时必须立即更换；2. 年限：即便行驶里程较少，通常轮胎橡胶在5至6年后也会加速老化，建议及时更替。',
    questionJa: 'タイヤの交換時期の目安は？',
    answerJa: '大きく2つの目安があります：1. 摩耗の限界（残り溝1.6mmを示す「スリップサイン」の露出）、2. 年数（走行距離が少なくても、ゴムは製造から5〜6年経過すると経年劣化が進むため安全のために点検・交換を推奨します）。',
  },
  {
    id: 'f3',
    category: 'service',
    question: '你们提供现场更换/搬运安装服务吗？也销售其他大牌轮胎吗？',
    answer: '除了代理及直营自主「KOMATSU」高性价比品牌轮胎外，我们也通过日本国内强大的批发网络支持普利司通、米其林、邓禄普等知名品牌的代理贩卖。我们支持来店拆装、四轮定位以及大客户配送服务。',
    questionJa: 'タイヤ取り付けサービスは行っていますか？他社ブランドの取り扱いは？',
    answerJa: '自社ブランド「KOMATSU」タイヤの直販の他にも、独自の流通網を活かし、ブリヂストン、ミシュラン、ダンロップ等の国内外有名メーカーの卸売・小売販売も可能です。店頭取付、ホイールアライメント調整、法人様向け配送サービス等も完備しています。',
  }
];

// 繁简与日文语言字典
export const TRANSLATIONS = {
  zh: {
    // Nav & Common
    langName: '日本語',
    navHome: '首页',
    navAbout: '会社概要',
    navProducts: '商品展示',
    navCalculator: '规格对碰',
    navFAQ: '常见问题',
    navContact: '预约询价',
    phoneCall: '咨询专线',
    emailContact: '邮件联系',
    
    // Slogan / Hero
    sloganTop: '东京都足立区 · 专业高品质轮胎贩卖',
    sloganBig: '匠心驱动，安全随行',
    sloganSub: '小松株式会社 (Komatsu Co., Ltd.) 竭诚为您服务。整合优质的采购供应链，提供轿车、货车、雪地胎等多种规格的高品质轮胎。',
    btnCatalog: '浏览轮胎目录',
    btnInquiry: '在线快捷询价',
    satisfaction: '客户满意度达 98.6%',
    tiresSold: '已售出轮胎万条以上',
    reliableService: '日本法人认证、正品保障',
    
    // Corporate Facts
    corpNumber: '法人番号',
    corpNumberVal: '6011801046241',
    corpName: '商号又は名称',
    corpNameVal: '小松株式会社',
    corpAddress: '总部所在地',
    corpAddressVal: '東京都足立区江北３丁目３０－１８',
    president: '代表取缔役 / 负责人',
    presidentVal: '小松 健太 (Kenta Komatsu)',
    established: '设立登记日期',
    establishedVal: '2016年10月12日',
    businessScope: '经营范围',
    businessScopeVal: '轮胎及轮毂进出口、国内批发与销售，汽车配件零售，车辆出差保养技术咨询服务。',
    
    // Strengths
    strengthTitle: '为什么选择小松株式会社？',
    strengthSub: '立足足立区，覆盖东京圈，服务全日本的精细化汽配专家',
    strength1Title: '超高性价比',
    strength1Desc: '扁平化供应链结构，直接让利于企事业单位及零售个人车主。',
    strength2Title: '品质全面把控',
    strength2Desc: '所有产品出厂均通过JIS（日本产业标准）或DOT等多项严苛安全认证。',
    strength3Title: '丰富规格现货',
    strength3Desc: '长期持备主流乘用车与商用轻卡现货，发货及配送迅速响应。',
    strength4Title: '法人合规担保',
    strength4Desc: '已在国税厅正式备案（法人番号: 6011801046241），开票合规，售后无忧。',

    // Products
    productTitle: '热销轮胎 · 取扱商品',
    productSub: '全规格，高性能，覆盖四季及多种出行路况',
    sport: '运动轿跑胎',
    comfort: '高端静音胎',
    eco: '绿色节能胎',
    suv: 'SUV 越野胎',
    winter: '防滑雪地胎',
    allTypes: '全部类型',
    specs: '轮胎规格',
    priceUnits: '日元',
    inquiryNow: '立即询价',
    perTire: '起 / 条',
    popularBadge: '热门推荐',
    
    // Calculator
    calcTitle: '智能轮胎规格对照计算器',
    calcSub: '帮助您快速推算原厂替换轮胎或升级轮毂后的尺寸偏差，保持时速表精准，行车安全第一。',
    calcInput1: '原车轮胎规格 (Current)',
    calcInput2: '拟选新规格 (New)',
    calcWidth: '胎面宽度 (mm)',
    calcAspect: '扁平比 (%)',
    calcDiameter: '轮毂尺寸 (inch)',
    calcSubmit: '开始对比分析',
    calcResultCompare: '对比分析结果',
    diameterDiff: '直径偏差',
    heightDiff: '离地高度偏差',
    speedoDiff: '时速表偏差 (时速100km/h时实际)',
    calcWarningLimit: '⚠️ 直径偏差超过 ±3%，可能导致操控性能不佳或车身摩擦。建议再次确认规格或咨询我们的轮胎专家！',
    calcSuccessMsg: '✅ 尺寸偏差处于非常安全的 ±3% 范围内。可以进行替换升级！',
    sidewall: '侧壁高度',
    totalDia: '轮胎总直径',
    circ: '轮胎周长',
    revs: '每公里转数',
    
    // Inquiry Form
    formTitle: '预约咨询与报价评估',
    formSub: '请填写下方卡片信息，资深销售专员将在1个工作日内免费为您发送轮胎批发/零售报价单！',
    formLabelName: '客户姓名 (或企业名称)',
    formLabelEmail: '联系邮箱',
    formLabelPhone: '联系电话 (日本国内拨打)',
    formLabelType: '意向轮胎类型',
    formLabelSize: '所需尺寸/规格 (例如：205/55R16)',
    formLabelQty: '采购数量',
    formLabelMsg: '附言或特殊技术要求',
    formPlaceholderName: '例如：小松太郎 或 株式会社AAA',
    formPlaceholderMsg: '如有特定的轮胎品牌偏好，或需要上门车店安装服务，请在此注明。',
    formSubmitBtn: '提交估价申请',
    formSuccessTitle: '提交成功！お申込みありがとうございます。',
    formSuccessDesc: '我们已收到您的询价与估算意向。由于您的法人所在地或联系电话格式正确，小松株式会社客服专员将在24小时内发送专属报价信函，敬请留意您的邮箱！',
    formSending: '正在提报您的估价单...',
    
    // Footer & Location
    workHours: '营业时间',
    workHoursVal: '周一至周五 09:00 - 18:00 (周末及节假日休业)',
    telNum: '商务热线',
    telVal: '03-5856-XXXX (代表)',
    copyright: '© 2026 小松株式会社. All rights reserved. (法人番号: 6011801046241)',
  },
  ja: {
    // Nav & Common
    langName: '中文',
    navHome: 'ホーム',
    navAbout: '会社概要',
    navProducts: '取扱商品',
    navCalculator: 'サイズ計算',
    navFAQ: 'よくある質問',
    navContact: 'お問い合わせ',
    phoneCall: 'お電話窓口',
    emailContact: 'メール連絡',
    
    // Slogan / Hero
    sloganTop: '東京都足立区 · 高品質タイヤ販売のプロフェッショナル',
    sloganBig: '確かな技術、確かな安全',
    sloganSub: '小松株式会社（Komatsu Co., Ltd.）の公式サイトです。経験豊富な調達網により、乗用車、トラック、スタッドレスタイヤ等、全サイズを適正価格でご提供いたします。',
    btnCatalog: '商品一覧を見る',
    btnInquiry: '簡単無料お見積もり',
    satisfaction: '満足度：98.6%',
    tiresSold: '累計販売数1万本以上',
    reliableService: '日本国法人認証・正規品保証',
    
    // Corporate Facts
    corpNumber: '法人番号',
    corpNumberVal: '6011801046241',
    corpName: '商号又は名称',
    corpNameVal: '小松株式会社',
    corpAddress: '本店所在地',
    corpAddressVal: '東京都足立区江北３丁目３０－１８',
    president: '代表取締役 / 責任者',
    presidentVal: '小松 健太 (Kenta Komatsu)',
    established: '設立登記年月日',
    establishedVal: '2016年10月12日',
    businessScope: '事業内容',
    businessScopeVal: 'タイヤおよびホイールの輸出入・国内卸売・小売販売、その他自動車用部品の調達、出張タイヤ点検コンサル業務。',
    
    // Strengths
    strengthTitle: '小松株式会社が選ばれる理由',
    strengthSub: '足立区を拠点に首都圏、さらには全国を繋ぐカーライフのパートナー',
    strength1Title: '徹底したコスト削減',
    strength1Desc: '中間マージンをカットした独自の流通ルートで、高品質タイヤを低価格でご提供します。',
    strength2Title: '安心の品質管理',
    strength2Desc: 'JIS（日本産業規格）またはDOT等の厳しい国際安全基準に合格した規格品のみを取り扱っています。',
    strength3Title: '幅広い在庫ラインアップ',
    strength3Desc: '乗用車汎用サイズから商用ライトトラックまで、豊富な在庫体制で迅速な納品を実現。',
    strength4Title: '安心の政府公認法人',
    strength4Desc: '国税庁にて正規登記済み（法人番号：6011801046241）。見積・インボイス対応も万全です。',

    // Products
    productTitle: '取扱商品 · タイヤ一覧',
    productSub: '全サイズ対応、高ライフ、多様な走行環境に適合する厳选タイヤ',
    sport: 'スポーツタイヤ',
    comfort: 'コンフォートタイヤ',
    eco: 'エコ・低燃費タイヤ',
    suv: 'SUV用・オフロード',
    winter: 'スタッドレスタイヤ',
    allTypes: '全タイプ',
    specs: 'タイヤサイズ',
    priceUnits: '円',
    inquiryNow: '見積もり依頼',
    perTire: '〜 / 本',
    popularBadge: '人気商品',

    // Calculator
    calcTitle: 'タイヤサイズ外径計算シミュレーター',
    calcSub: 'インチアップやタイヤ交換時の外径偏差を表示します。スピードメーターの誤差を予防し、安全運転に貢献します。',
    calcInput1: '元のタイヤサイズ (Current)',
    calcInput2: '新品タイヤサイズ (New)',
    calcWidth: 'タイヤ幅 (mm)',
    calcAspect: '偏平率 (%)',
    calcDiameter: 'ホイール径 (インチ)',
    calcSubmit: 'タイヤ比較計算を行う',
    calcResultCompare: 'シミュレーション結果',
    diameterDiff: '外径との差',
    heightDiff: '車高への影響',
    speedoDiff: 'メーター誤差 (時速100km/h走行時の実速目安)',
    calcWarningLimit: '⚠️ 外径の差が ±3% を超えています。スピードメーターの車検基準を満たさない可能性、車体への干渉リスクがあります。サイズ確認を推奨します。',
    calcSuccessMsg: '✅ サイズ差は許容範囲の ±3% 以内に収まっています。タイヤの互換性に問題ありません。',
    sidewall: 'タイヤ側面高',
    totalDia: 'タイヤ外径',
    circ: 'タイヤ外周',
    revs: '1kmあたりの回転数',
    
    // Inquiry Form
    formTitle: 'お見積もり＆ご予約フォーム',
    formSub: '以下の項目にご入力ください。専任スタッフがお見積を作成し、1営業日内に丁寧に対応させていただきます。',
    formLabelName: 'お名前 (会社名・ご担当者名)',
    formLabelEmail: 'メールアドレス',
    formLabelPhone: 'お電話番号 (日本)',
    formLabelType: 'お探しのタイヤタイプ',
    formLabelSize: 'タイヤサイズ (例：205/55R16)',
    formLabelQty: 'タイヤのご希望本数',
    formLabelMsg: 'メッセージ・ご要望',
    formPlaceholderName: '例：小松太郎 or 株式会社AAA',
    formPlaceholderMsg: '特定のメーカーご希望や出張取付等のご相談があればこちらに詳しくご記入ください。',
    formSubmitBtn: '見積もりを申し込む',
    formSuccessTitle: 'お申し込みを受付致しました。',
    formSuccessDesc: 'お問い合わせありがとうございます。２４時間以内にお見積り書もしくはご案内のメールをお送りいたしますので、よろしくお願いいたします。',
    formSending: '送信中...',

    // Footer & Location
    workHours: '営業時間',
    workHoursVal: '月曜日 〜 金曜日 09:00 - 18:00 (土・日・祝祭日除く)',
    telNum: 'お電話窓口',
    telVal: '03-5856-XXXX (代表)',
    copyright: '© 2026 小松株式会社. All rights reserved. (法人番号: 6011801046241)',
  }
};
